dist: jammy
language: php

php:
  - 8.2

addons:
  chrome: stable

before_install:
  - mkdir -p ~/.ssh
  - echo "$SSH_KEY" | base64 -d > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - nvm install 20
  - node -v
  - npm -v

install:
  - npm install
  - composer install

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - npm run build
  - php -S localhost:8000 -t public &

script:
  - npm run test:headless

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
