services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "
      composer install &&
      php artisan key:generate &&

      php artisan serve --host=0.0.0.0 --port=80
      "
    environment:
      - APP_ENV=prod
      - APP_DEBUG=true
      - APP_KEY=base64:GENERAR_APP_KEY
      - DB_CONNECTION=pgsql
      - DATABASE_URL=process.env.DATABASE_URL
      - PGHOST=process.env.PGHOST
      - PGUSER=process.env.PGUSER
      - PGDATABASE=process.env.PGDATABASE
      - PGPASSWORD=process.env.PGPASSWORD
