services:
  laravel:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    working_dir: /var/www/html
    command: >
      sh -c "
      composer install &&
      php artisan key:generate &&
      php artisan migrate &&
      php artisan db:seed &&
      php artisan serve --host=0.0.0.0 --port=80
      "
    depends_on:
      - db
      - pgadmin

  # nginx:
  #   container_name: nginx
  #   image: nginx:stable-alpine
  #   restart: always
  #   ports:
  #     - "85:80"
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - app-network
  #   depends_on:
  #     - laravel
  #     - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
