services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/public
    command: apache2-foreground
